# Docker 运行时读取的配置文件, 有些参数会被 docker-compose 中的环境变量覆盖
# 具体参考 deploy/start 下 docker-compose 和 .env 文件
# 例如: MYSQL_PORT 会覆盖 [Mysql] 下的 Port

[Server]
AppMode = "release" # debug, release
BackPort = ":8765"  # 前台服务端口
FrontPort = ":5678" # 后台服务端口

# 线上部署建议将 Secret 和 Issuer 修改成其他随机值
[JWT]
Secret = "abc123321"
Expire = 24             # 过期时间 (小时)
Issuer = "gin-vue-blog"

# 优先会读取 docker-compose 中的环境变量，这里基本不用动
[Mysql]
Host = "172.12.0.3"
Port = "3306"
Config = ""
Dbname = "gvb"
Username = "root"
Password = "12345566"
# 日志级别 silent, error, warn, info, 默认 info, slient 相当于关闭日志
LogMode = "error"

# 优先会读取 docker-compose 中的环境变量，这里基本不用动
[Redis]
DB = 7
Addr = "172.12.0.2:6379"
Password = "66554321"

# 线上部署建议将 Name 和 Salt 修改成其他随机值
[Session]
Name = "mysession"
Salt = "salt"
MaxAge = 600       # 秒

# 配置发送验证码账号信息
[Email]
Host = "smtp.163.com"       # 服务器地址, 例如 smtp.qq.com 前往要发邮件的邮箱查看其 smtp 协议
Port = 465                  # 前往要发邮件的邮箱查看其 smtp 协议端口, 大多为 465
From = ""     # 发件人 (邮箱)
IsSSL = true                # 是否开启 SSL
Secret = "" # 密钥, 不是邮箱登录密码, 是开启 smtp 服务后获取的一串验证码
Nickname = ""           # 发件人昵称, 通常为自己的邮箱名

[Captcha]
SendEmail = true # 通过邮箱发送验证码
ExpireTime = 15  # 过期时间 (分钟)

# 根据需求调整
[Zap]
Level = "error"        # 日志级别: debug, info, warn, error, dpanic, panic, fatal, 默认 info
Format = "console"     # 输出格式: console, json
Prefix = "[GIN-BLOG] " # 日志前缀
Directory = "log"      # 存放日志的文件夹
ShowLine = false       # 是否显示哪行调用
LogInConsole = false   # 是否输出到控制台

# 线上部署建议使用七牛云存储, 自行去七牛云创建对象存储服务
# https://developer.qiniu.com/kodo/1233/console-quickstart
# 不使用七牛云可以选择本地存储, 上传文件会存储在你的服务器上
[Upload]
OssType = "local"             # 控制存储: local、qiniu
Path = "public/uploaded"      # 本地文件访问路径 (OssType="local" 才生效)
StorePath = "public/uploaded" # 本地文件上传路径 (OssType="local" 才生效)
# Markdown 目前只支持本地上传 (目前使用前端导出, 该配置无效)
MdPath = "public/markdown/"      # Markdown 访问路径
MdStorePath = "public/markdown/" # Markdown 上传路径

# OssType = "Qiniu" 需要完善以下信息
[Qiniu]
ImgPath = ""          # 外链
Zone = ""
Bucket = ""
AccessKey = ""
SecretKey = ""
UseHttps = false      # 是否使用 https 加速
UseCdnDomains = false # 上传是否使用 CDN 上传加速
